const M={dashboard:'Mein Dashboard',dienstplan:'Dienstplanung',news:'Interne Nachrichten',dokumente:'Dokumentencenter',antraege:'Urlaub & Anträge',diensttausch:'Diensttausch',werkstatt:'Werkstatt & Fahrzeugmeldungen',leitstelle:'Leitstellenmeldungen',hoefe:'Betriebshöfe intern',akademie:'ROGIS Akademie',telefonbuch:'Telefonbuch & Ansprechpartner',it:'IT & Zugänge',formulare:'Formularcenter',benutzer:'Benutzer & Rollen',fremdverkehr:'Fremdverkehr'};
const R={
'Geschäftsführung':['dashboard','dienstplan','news','dokumente','antraege','diensttausch','werkstatt','leitstelle','hoefe','akademie','telefonbuch','it','formulare','fremdverkehr'],
'Betriebsleitung':['dashboard','dienstplan','news','dokumente','antraege','diensttausch','werkstatt','leitstelle','hoefe','akademie','telefonbuch','it','formulare','fremdverkehr'],
'Disposition':['dashboard','dienstplan','news','dokumente','antraege','diensttausch','werkstatt','leitstelle','hoefe','telefonbuch','it','formulare','fremdverkehr'],
'Leitstelle':['dashboard','dienstplan','news','dokumente','werkstatt','leitstelle','hoefe','telefonbuch','it','formulare','fremdverkehr'],
'Werkstatt/Technik':['dashboard','news','dokumente','werkstatt','hoefe','telefonbuch','it','formulare'],
'Fahrdienst':['dashboard','dienstplan','news','dokumente','antraege','diensttausch','akademie','telefonbuch','it','formulare'],
'Ausbildung':['dashboard','dienstplan','news','dokumente','antraege','diensttausch','akademie','telefonbuch','it','formulare'],
'Reinigung/Hofdienst':['dashboard','dienstplan','news','dokumente','antraege','hoefe','telefonbuch','it','formulare'],
'Administration':Object.keys(M),
'Fremdverkehr/Subunternehmer':['dashboard','dokumente','fremdverkehr','it']};
const contacts=[
{name:'Andreas Neubaum',position:'Geschäftsführer',department:'Geschäftsführung',location:'Zentrale'},
{name:'Emil Breitbau',position:'Betriebsleiter Bereich Transport',department:'Betriebsleitung Transport',location:'Zentrale'},
{name:'Tim Neumann',position:'Betriebsleiter Bereich Transport',department:'Betriebsleitung Transport',location:'Zentrale'},
{name:'Robert Edward Davis',position:'Ausbildungsleiter',department:'ROGIS Akademie',location:'Zentrale'},
{name:'Oliver Schesch',position:'Disponent',department:'Disposition',location:'Mitte'},
{name:'Patric Gehen',position:'Disponent',department:'Disposition',location:'Mitte'},
{name:'Thomas Bongkar',position:'Leiter Außendienst / Fremdverkehr',department:'Außendienst',location:'Übergreifend'},
{name:'Sebastian Blinkeisen',position:'Leitstellenmitarbeiter',department:'Leitstelle / Verkehrssteuerung',location:'Mitte'},
{name:'Jeffrey Berken',position:'Nutzfahrzeugmechatroniker',department:'Werkstatt / Technik',location:'Mitte'}];
const SALT='5d716d73646cd568639ca3b0e821e1fc',HASH='57e999bf44b24891453a15a6695beda13c91aefb07f73433bc35a0fc3e1ba138',IT=150000,enc=new TextEncoder(),shared=new Set(['news','dokumente','leitstelle','hoefe','akademie']);
const perms=u=>u.username==='emil.breitbau'?Object.keys(M):R[u.role]||[];
const manage=(u,k)=>u.username==='emil.breitbau'||u.role==='Administration'||(['Geschäftsführung','Betriebsleitung'].includes(u.role)&&k!=='benutzer')||({werkstatt:['Werkstatt/Technik'],leitstelle:['Leitstelle','Disposition'],diensttausch:['Disposition'],akademie:['Ausbildung'],hoefe:['Disposition'],fremdverkehr:['Disposition']}[k]||[]).includes(u.role);
const hex=a=>[...a].map(b=>b.toString(16).padStart(2,'0')).join(''),unhex=s=>Uint8Array.from(s.match(/../g)||[],x=>parseInt(x,16)),rnd=(n=24)=>{let a=new Uint8Array(n);crypto.getRandomValues(a);return hex(a)};
async function digest(s){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(s))))}
async function pwh(p,s,it=IT){const k=await crypto.subtle.importKey('raw',enc.encode(p),'PBKDF2',false,['deriveBits']);return hex(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:unhex(s),iterations:it},k,256)))}
async function makepw(p){const s=rnd(16);return `${IT}:${s}:${await pwh(p,s)}`}
async function checkpw(p,v){const [i,s,h]=String(v||'').split(':');return !!h&&(await pwh(p,s,Number(i)))===h}
const out=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...h}}),bad=(s,e)=>out({error:e},s),str=(b,k,n=5000)=>typeof b?.[k]==='string'?b[k].trim().slice(0,n):'';
function cv(r,n){return (r.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(n+'='))?.slice(n.length+1)||''}
async function body(r){if(!['POST','PATCH','DELETE'].includes(r.method))return{};if(!(r.headers.get('content-type')||'').startsWith('application/json'))throw Object.assign(Error('JSON erforderlich.'),{status:415});const t=await r.text();if(t.length>1000000)throw Object.assign(Error('Eingabe ist zu groß.'),{status:413});try{return t?JSON.parse(t):{}}catch{throw Object.assign(Error('Ungültige Eingabe.'),{status:400})}}
async function init(db){await db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT UNIQUE NOT NULL,name TEXT NOT NULL,role TEXT NOT NULL,password TEXT NOT NULL,active INTEGER NOT NULL DEFAULT 1);CREATE TABLE IF NOT EXISTS records(id INTEGER PRIMARY KEY AUTOINCREMENT,area TEXT NOT NULL,owner INTEGER NOT NULL DEFAULT 0,title TEXT NOT NULL,body TEXT NOT NULL,status TEXT NOT NULL,created TEXT NOT NULL,extra TEXT NOT NULL DEFAULT '{}');CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,uid INTEGER NOT NULL,csrf TEXT NOT NULL,expires INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY AUTOINCREMENT,actor INTEGER NOT NULL,action TEXT NOT NULL,created TEXT NOT NULL);`);
let e=await db.prepare('SELECT id FROM users WHERE username=?').bind('emil.breitbau').first();if(!e){await db.prepare('INSERT INTO users(id,username,name,role,password,active) VALUES(1,?,?,?,?,1)').bind('emil.breitbau','Emil Breitbau','Betriebsleitung',`${IT}:${SALT}:${HASH}`).run();const n=new Date().toISOString();await db.batch([db.prepare('INSERT INTO records(area,owner,title,body,status,created,extra) VALUES(?,?,?,?,?,?,?)').bind('news',1,'Wagen 1603 gehört zur Fahrschule','Wagen 1603 wird als Fahrschulbus geführt und nicht regulär im Linien- oder Reserveverkehr disponiert.','Veröffentlicht',n,'{}'),db.prepare('INSERT INTO records(area,owner,title,body,status,created,extra) VALUES(?,?,?,?,?,?,?)').bind('akademie',1,'ROGIS Akademie','Ausbildung und Fahrschule werden durch die Ausbildungsleitung koordiniert. Wagen 1603 steht der Fahrschule zur Verfügung.','Veröffentlicht',n,'{}')])}await db.prepare('DELETE FROM sessions WHERE expires<?').bind(Date.now()).run()}
async function sess(r,db){const raw=cv(r,'rogis_session');if(!raw)return{};const token=await digest(raw),s=await db.prepare('SELECT * FROM sessions WHERE token=? AND expires>?').bind(token,Date.now()).first();if(!s)return{};const u=await db.prepare('SELECT id,username,name,role,active FROM users WHERE id=? AND active=1').bind(s.uid).first();return{s,u,token}}
async function audit(db,u,a){await db.prepare('INSERT INTO audit(actor,action,created) VALUES(?,?,?)').bind(u.id,a,new Date().toISOString()).run()}
export async function onRequest({request,env}){if(!env.DB)return bad(503,'Datenbank ist noch nicht verbunden.');const db=env.DB;await init(db);const url=new URL(request.url),p=url.pathname;let b={};try{b=await body(request)}catch(e){return bad(e.status||400,e.message)}const z=await sess(request,db),u=z.u,s=z.s,allowed=k=>u&&perms(u).includes(k);
if(p==='/api/login'&&request.method==='POST'){const n=str(b,'username',80).toLowerCase(),pw=str(b,'password',200),x=await db.prepare('SELECT * FROM users WHERE username=? AND active=1').bind(n).first();if(!x||!(await checkpw(pw,x.password)))return bad(401,'Benutzername oder Passwort ist nicht korrekt.');const raw=rnd(32),token=await digest(raw),csrf=rnd(24);await db.prepare('INSERT INTO sessions(token,uid,csrf,expires) VALUES(?,?,?,?)').bind(token,x.id,csrf,Date.now()+28800000).run();await audit(db,x,'Anmeldung');return out({ok:true},200,{'set-cookie':`rogis_session=${raw}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=28800`})}
if(p==='/api/public-request'&&request.method==='POST'){const c=str(b,'category'),name=str(b,'name',100),email=str(b,'email',254),msg=str(b,'body');if(!['Kontakt','Fundsache','Bewerbung','Barrierefreiheit','Presse','Tarifberatung'].includes(c)||name.length<2||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||msg.length<10)return bad(400,'Bitte alle Angaben prüfen.');const q=await db.prepare("SELECT count(*) n FROM records WHERE area='kontakt' AND created>?").bind(new Date(Date.now()-3600000).toISOString()).first();if(Number(q?.n||0)>50)return bad(429,'Bitte später erneut versuchen.');const extra=JSON.stringify({name,email,assignedTo:'Emil Breitbau',assignedRole:'Betriebsleiter Bereich Transport'}),r=await db.prepare('INSERT INTO records(area,owner,title,body,status,created,extra) VALUES(?,?,?,?,?,?,?)').bind('kontakt',1,c,msg,'Eingegangen',new Date().toISOString(),extra).run();return out({id:Number(r.meta.last_row_id)},201)}
if(!p.startsWith('/api/'))return bad(404,'Nicht gefunden.');if(!u)return bad(401,'Bitte melden Sie sich an.');if(['POST','PATCH','DELETE'].includes(request.method)&&p!=='/api/logout'&&request.headers.get('x-csrf-token')!==s.csrf)return bad(403,'Sitzung ungültig. Bitte erneut anmelden.');
if(p==='/api/me')return out({user:u,permissions:perms(u),manage:perms(u).filter(k=>manage(u,k)),csrf:s.csrf,roles:allowed('benutzer')?R:undefined});
if(p==='/api/logout'&&request.method==='POST'){await db.prepare('DELETE FROM sessions WHERE token=?').bind(z.token).run();return out({ok:true},200,{'set-cookie':'rogis_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0'})}
if(p==='/api/password'&&request.method==='POST'){const x=await db.prepare('SELECT password FROM users WHERE id=?').bind(u.id).first(),a=str(b,'current',200),n=str(b,'password',200);if(!(await checkpw(a,x.password))||n.length<12)return bad(400,'Aktuelles Passwort prüfen; das neue Passwort muss mindestens 12 Zeichen haben.');await db.prepare('UPDATE users SET password=? WHERE id=?').bind(await makepw(n),u.id).run();await audit(db,u,'Passwort geändert');return out({ok:true})}
if(p==='/api/contacts'&&request.method==='GET'){if(!allowed('telefonbuch'))return bad(403,'Keine Berechtigung.');return out(contacts)}
if(p==='/api/inbox'&&request.method==='GET'){if(!manage(u,'formulare')&&!manage(u,'news'))return bad(403,'Keine Berechtigung.');return out((await db.prepare("SELECT r.*,u.name author FROM records r LEFT JOIN users u ON u.id=r.owner WHERE area='kontakt' ORDER BY r.id DESC").all()).results)}
if(p==='/api/users'){if(!allowed('benutzer'))return bad(403,'Keine Berechtigung.');if(request.method==='GET'){return out({users:(await db.prepare('SELECT id,username,name,role,active FROM users ORDER BY name').all()).results,audit:(await db.prepare('SELECT a.action,a.created,u.name FROM audit a JOIN users u ON u.id=a.actor ORDER BY a.id DESC LIMIT 30').all()).results})}if(request.method==='POST'){const username=str(b,'username',80),name=str(b,'name',100),role=str(b,'role'),pw=str(b,'password',200);if(!/^[a-z0-9._-]{3,60}$/.test(username)||!R[role]||name.length<2||pw.length<12)return bad(400,'Name, Benutzername, Rolle und Passwort prüfen.');if(await db.prepare('SELECT id FROM users WHERE username=?').bind(username).first())return bad(409,'Benutzername bereits vergeben.');await db.prepare('INSERT INTO users(username,name,role,password,active) VALUES(?,?,?,?,1)').bind(username,name,role,await makepw(pw)).run();await audit(db,u,'Benutzer angelegt: '+username);return out({ok:true},201)}}
if(p.startsWith('/api/records/')){const a=p.split('/')[3],id=Number(p.split('/')[4]||0);if(!M[a]||!allowed(a))return bad(403,'Keine Berechtigung.');const sh=shared.has(a),mgr=manage(u,a);if(request.method==='GET'){const q=sh||mgr?'SELECT r.*,u.name author FROM records r LEFT JOIN users u ON u.id=r.owner WHERE area=? ORDER BY r.id DESC':'SELECT r.*,u.name author FROM records r LEFT JOIN users u ON u.id=r.owner WHERE area=? AND owner=? ORDER BY r.id DESC',args=sh||mgr?[a]:[a,u.id];return out((await db.prepare(q).bind(...args).all()).results)}if(request.method==='POST'){if(sh&&!mgr)return bad(403,'Keine Berechtigung zum Veröffentlichen.');const title=str(b,'title',160),msg=str(b,'body'),extra={};if(title.length<3||msg.length<3)return bad(400,'Bitte Betreff und Beschreibung ausfüllen.');if(a==='antraege'){extra.from=str(b,'from',10);extra.to=str(b,'to',10)}if(a==='werkstatt'){const v=str(b,'vehicle',10);if(!/^\d{4}$/.test(v))return bad(400,'Bitte Wagen wählen.');extra.vehicle=v;extra.priority=str(b,'priority',50)}const r=await db.prepare('INSERT INTO records(area,owner,title,body,status,created,extra) VALUES(?,?,?,?,?,?,?)').bind(a,u.id,title,msg,sh?'Veröffentlicht':'Eingegangen',new Date().toISOString(),JSON.stringify(extra)).run();await audit(db,u,M[a]+': Eintrag erstellt');return out({id:Number(r.meta.last_row_id)},201)}if(request.method==='PATCH'&&id){const st=str(b,'status');if(!mgr||!['In Bearbeitung','Genehmigt','Abgelehnt','Erledigt'].includes(st))return bad(403,'Keine Berechtigung.');await db.prepare('UPDATE records SET status=? WHERE id=? AND area=?').bind(st,id,a).run();await audit(db,u,`${a} #${id}: ${st}`);return out({ok:true})}}
return bad(404,'Nicht gefunden.')}